title: Qi Li # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer Working with Data Related Projects
  <br><br>
  <a href="https://www.linkedin.com/in/qi-l-6576b326/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
